version: "2.1"
services:
  nginx:
    build: .
    container_name: vod-server-dev
    environment:
      - PUID=3010
      - PGID=3010
      - TZ=America/Chicago
      - RENDER_GID=105 # Intel Quicksync creates this group; need the ID. Tip: `stat /dev/dri/renderD128`
    volumes:
      - ./root/etc/cont-init.d/41-config:/etc/cont-init.d/41-config
      - ./root/nginx-configs/nginx/site-confs/default.conf:/config/nginx/site-confs/default.conf
      - ./root/vod-server-webapp:/vod-server-webapp
      - /docker-persistent/wow-videos/video_files:/vod-server-webapp/nginx_www/video_files
      - /docker-persistent/wow-videos/thumbnails:/thumbnails
      #- /docker-persistent/wow-videos/video_meta:/video_meta
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 19080:80
      - 19443:443
#    restart: unless-stopped
