#!/usr/bin/with-contenv bash

cp -r /nginx-configs/* /config

chown -R $PUID:$PGID /vod-server-webapp

mkdir /thumbnails
chown -R $PUID:$PGID /thumbnails

mkdir /video_meta
chown -R $PUID:$PGID /video_meta

